# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestKomplettbokning():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_komplettbokning(self):
    # Test name: komplett_bokning
    # Step # | name | target | value
    # 1 | open | /Booking/Booking/Index/stockholm | 
    self.driver.get("https://bokapass.nemoq.se/Booking/Booking/Index/stockholm")
    # 2 | setWindowSize | 1936x1056 | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | name=StartNextButton | 
    self.driver.find_element(By.NAME, "StartNextButton").click()
    # 4 | click | id=AcceptInformationStorage | 
    self.driver.find_element(By.ID, "AcceptInformationStorage").click()
    # 5 | click | name=Next | 
    self.driver.find_element(By.NAME, "Next").click()
    # 6 | click | css=.radio:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".radio:nth-child(1)").click()
    # 7 | click | name=Next | 
    self.driver.find_element(By.NAME, "Next").click()
    # 8 | click | name=TimeSearchFirstAvailableButton | 
    self.driver.find_element(By.NAME, "TimeSearchFirstAvailableButton").click()
    # 9 | click | css=.pointer | 
    self.driver.find_element(By.CSS_SELECTOR, ".pointer").click()
    # 10 | click | css=.btn-toolbar:nth-child(13) > #booking-next | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-toolbar:nth-child(13) > #booking-next").click()
    # 11 | click | id=Customers_0__BookingFieldValues_0__Value | 
    self.driver.find_element(By.ID, "Customers_0__BookingFieldValues_0__Value").click()
    # 12 | type | id=Customers_0__BookingFieldValues_0__Value | Filip
    self.driver.find_element(By.ID, "Customers_0__BookingFieldValues_0__Value").send_keys("Filip")
    # 13 | type | id=Customers_0__BookingFieldValues_1__Value | Asplund
    self.driver.find_element(By.ID, "Customers_0__BookingFieldValues_1__Value").send_keys("Asplund")
    # 14 | click | id=Customers_0__Services_0__IsSelected | 
    self.driver.find_element(By.ID, "Customers_0__Services_0__IsSelected").click()
    # 15 | click | name=Next | 
    self.driver.find_element(By.NAME, "Next").click()
    # 16 | click | name=Next | 
    self.driver.find_element(By.NAME, "Next").click()
    # 17 | click | id=EmailAddress | 
    self.driver.find_element(By.ID, "EmailAddress").click()
    # 18 | click | id=EmailAddress | 
    self.driver.find_element(By.ID, "EmailAddress").click()
    # 19 | doubleClick | id=EmailAddress | 
    element = self.driver.find_element(By.ID, "EmailAddress")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 20 | click | id=EmailAddress | 
    self.driver.find_element(By.ID, "EmailAddress").click()
    # 21 | click | id=EmailAddress | 
    self.driver.find_element(By.ID, "EmailAddress").click()
    # 22 | doubleClick | id=EmailAddress | 
    element = self.driver.find_element(By.ID, "EmailAddress")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 23 | click | id=EmailAddress | 
    self.driver.find_element(By.ID, "EmailAddress").click()
    # 24 | type | id=EmailAddress | filip.asplund+pass@gmail.com
    self.driver.find_element(By.ID, "EmailAddress").send_keys("filip.asplund+pass@gmail.com")
    # 25 | click | id=ConfirmEmailAddress | 
    self.driver.find_element(By.ID, "ConfirmEmailAddress").click()
    # 26 | type | id=ConfirmEmailAddress | filip.asplund+pass@gmail.com
    self.driver.find_element(By.ID, "ConfirmEmailAddress").send_keys("filip.asplund+pass@gmail.com")
    # 27 | click | id=PhoneNumber | 
    self.driver.find_element(By.ID, "PhoneNumber").click()
    # 28 | type | id=PhoneNumber | 0763073421
    self.driver.find_element(By.ID, "PhoneNumber").send_keys("0763073421")
    # 29 | click | id=ConfirmPhoneNumber | 
    self.driver.find_element(By.ID, "ConfirmPhoneNumber").click()
    # 30 | type | id=ConfirmPhoneNumber | 0763073421
    self.driver.find_element(By.ID, "ConfirmPhoneNumber").send_keys("0763073421")
    # 31 | click | id=SelectedContacts_0__IsSelected | 
    self.driver.find_element(By.ID, "SelectedContacts_0__IsSelected").click()
    # 32 | click | id=SelectedContacts_1__IsSelected | 
    self.driver.find_element(By.ID, "SelectedContacts_1__IsSelected").click()
    # 33 | click | id=SelectedContacts_2__IsSelected | 
    self.driver.find_element(By.ID, "SelectedContacts_2__IsSelected").click()
    # 34 | click | id=SelectedContacts_3__IsSelected | 
    self.driver.find_element(By.ID, "SelectedContacts_3__IsSelected").click()
    # 35 | click | name=Next | 
    self.driver.find_element(By.NAME, "Next").click()
    # 36 | click | name=Next | 
    self.driver.find_element(By.NAME, "Next").click()
  
